### ISSUE TITLE
Module docker is DEPRECATED

### ISSUE THREAD

**Issue by msavrasov** [mfominov/ansible-docker-portainer#1]
Module docker is DEPRECATED in ansible 2.2

**Comment by msavrasov** [comment]
- name: Start Portainer
  become: yes
  **docker_container:** 
    image: "{{ portainer_image_name }}"
    state: started
    name: "{{ portainer_container_name }}"
    restart_policy: unless-stopped
    volumes:
      - "{{ portainer_storage_directory }}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    **published_ports:**
      - "{{ portainer_publish_port }}:9000"

**Comment by mfominov** [comment]
Resolved
